### ISSUE TITLE
The tepid-discovery program reported an error, how can i solve this error? The details are as follows.

### ISSUE THREAD

**Issue by qu4tion** [ListerLab/TEPID#20]
******* WARNING: File /tmp/pybedtools.lFWTyl.tmp has inconsistent naming convention for record:**
 NC_000932.1 35  259 A01045:564:H3V3JDSX2:1:1351:24053:4570  disc
                                                                                                        
 ******* WARNING: File /tmp/pybedtools.lFWTyl.tmp has inconsistent naming convention for record:**
 NC_000932.1 35  259 A01045:564:H3V3JDSX2:1:1351:24053:4570  disc
 
 Processing TE annotation
 Finding deletions
   indexing bam file
 Finding insertions
 **Error: no reads intersecting TEs found**

**Comment by wrn2333** [comment]
I have the same problem. How did you solve it
