### ISSUE TITLE
samtool error during "Sorting alignment" step of TEPID-map

### ISSUE THREAD

**Issue by DjampaK** [ListerLab/TEPID#3]
Hello, 

First of all, thank you for this tool which seems to be perfect for the analysis I need to do.
Trying to run it for the first time, an error occurs with samtools (version 1.7) during the "Sorting alignment" step : 
`Converting to bam
Sorting alignment
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files`
Currently, the command in TEPID/Scripts/tepid-map script is : 
`samtools sort -@ $proc "${fname}_unsort.bam" "${fname}"`
I suggest to replace it by the following one and it execute without error:  
`samtools sort -@ $proc "${fname}_unsort.bam" > "${fname}.bam"`

Regards,
DK

**Comment by timoast** [comment]
Hi, sorry for the delay here but this should be fixed as of 2b371bc5206e7a31b919d6e8dd31553d8f79fde5
